title = "Haruaki Tamada"
baseurl = "https://tamada.github.io"
theme = ["github.com/tamada/hugo_theme_mod", "github.com/nunocoracao/blowfish/v2"]

[module]
  [[module.imports]]
    path = "github.com/tamada/hugo_theme_mod"
