enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true
summaryLength = 300

[pagigation]
pagerSize = 6

[homepage]
layout = "page"
cardView = true

[list]
cardView = true
groupByYear = false
limit = 6
showSummary = true
showTaxonomies = true
showBreadcrumbs = true

[article]
showAuthor = false
showBreadcrumbs = true
showHeadingAnchors = true
showReadingTime = false
showTaxonomies = true
